trigger:
- master

resources:
  containers:
    - container: 'danger-android'
      image: 'meilcli/danger-android'
      
jobs:
  - job: Danger_PR
    displayName: Danger PR
    pool:
      vmImage: 'ubuntu-latest'
    container: 'danger-android'
    steps:
      - script: 'danger --dangerfile=.danger/danger-pr --danger_id=1'
        env:
          DANGER_GITHUB_API_TOKEN: $(DANGER_GITHUB_API_TOKEN)
  - job: Build
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          publishJUnitResults: false
          tasks: ':app:lint'
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          publishJUnitResults: false
          tasks: ':app:ktlintCheck'
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          publishJUnitResults: false
          tasks: ':app:test'
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'appBinary'
          targetPath: 'app/build'
  - job: Danger_App
    displayName: Danger App
    dependsOn:
      - Build
    condition: always()
    pool:
      vmImage: 'ubuntu-latest'
    container: 'danger-android'
    steps:
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: 'appBinary'
          targetPath: 'app/build'
      - script: 'danger --dangerfile=.danger/danger-app --danger_id=2'
        env:
          DANGER_GITHUB_API_TOKEN: $(DANGER_GITHUB_API_TOKEN)
