trigger:
- master

resources:
  containers:
    - container: 'danger-android'
      image: 'meilcli/danger-android'
      
jobs:
  - job: Danger_PR
    displayName: Danger PR
    pool:
      vmImage: 'ubuntu-16.04'
    container: 'danger-android'
    steps:
      - script: 'danger --dangerfile=.danger/danger-pr --danger_id=1'
        env:
          DANGER_GITHUB_API_TOKEN: $(DANGER_GITHUB_API_TOKEN)
      - script: 'echo ##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_8_X64)/bin'
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          publishJUnitResults: false
          tasks: ':app:lint'
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          publishJUnitResults: false
          tasks: ':app:ktlintCheck'
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          publishJUnitResults: false
          tasks: ':app:test'
      - script: 'danger --dangerfile=.danger/danger-app --danger_id=2 pr https://github.com/MeilCli/AzurePipelineAndroidSample/pull/1'
        condition: always()
        env:
          DANGER_GITHUB_API_TOKEN: $(DANGER_GITHUB_API_TOKEN)
