trigger:
- master

resources:
  containers:
    - container: 'danger-android'
      image: 'meilcli/danger-android'
      
jobs:
  - job: TestBuild
    displayName: Test Build
    pool:
      vmImage: 'ubuntu-latest'
    container: 'danger-android'
    steps:
      - script: 'danger --dangerfile=.danger/danger-pr --danger_id=1'
      - task: Gradle@2
        inputs:
          tasks: ':app:lint'
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
      - task: Gradle@2
        inputs:
          tasks: ':app:ktlintCheck'
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
      - task: Gradle@2
        inputs:
          tasks: ':app:test'
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
      - script: 'danger --dangerfile=.danger/danger-app --danger_id=2'
