trigger:
- master

resources:
  containers:
    - container: 'danger-android'
      image: 'meilcli/danger-android'
      
jobs:
  - job: TestBuild
    displayName: Test Build
    pool:
      vmImage: 'ubuntu-latest'
    container: 'danger-android'
    steps:
      - script: 'danger --dangerfile=.danger/danger-pr --danger_id=1'
      - script: 'chmod +x gradlew'
      - script: 'ls /usr/local'
      - script: 'ls /usr/local/lib'
      - script: './gradlew :app:lint'
      - script: './gradlew :app:ktlintCheck'
      - script: './gradlew :app:test'
      - script: 'danger --dangerfile=.danger/danger-app --danger_id=2'
